# Generated by Django 5.2.7 on 2025-10-27 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_test_allow_immediate_review_test_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_key',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='rubric_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq_single', 'MCQ (Single Answer)'), ('mcq_multi', 'MCQ (Multiple Answers)'), ('true_false', 'True / False'), ('fill_in', 'Fill in the Blank'), ('matching', 'Matching'), ('short', 'Short Answer'), ('essay', 'Essay')], default='short', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('test', 'student', 'attempt_number')},
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
