# Generated by Django 5.2.7 on 2025-10-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_testattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq_single', 'MCQ (Single Answer)'), ('mcq_multi', 'MCQ (Multiple Answers)'), ('true_false', 'True / False'), ('fill_in', 'Fill in the Blank'), ('matching', 'Matching'), ('short', 'Short Answer'), ('essay', 'Essay'), ('numerical', 'Numerical')], default='short', max_length=20),
        ),
    ]
