# Generated by Django 5.2.7 on 2025-11-19 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_notification_supportticket_certificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_date']},
        ),
        migrations.AlterModelOptions(
            name='markedquestion',
            options={'ordering': ['marked_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='testanswer',
            options={'ordering': ['question__id']},
        ),
        migrations.AlterModelOptions(
            name='testattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student', '-issued_date'], name='questions_c_student_83d6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_code'], name='questions_c_certifi_701191_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='questions_n_user_id_d90c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='questions_n_is_read_f05011_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'topic'], name='questions_q_subject_c51aee_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['author', '-created_at'], name='questions_q_author__17798a_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['subject', 'topic'], name='questions_r_subject_688683_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', '-created_at'], name='questions_s_user_id_00a371_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', '-created_at'], name='questions_s_status_712298_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority', 'status'], name='questions_s_priorit_74a9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['subject', '-created_at'], name='questions_t_subject_b02efd_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['created_by', '-created_at'], name='questions_t_created_592c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['student', '-started_at'], name='questions_t_student_082266_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', '-started_at'], name='questions_t_test_id_e4ab5a_idx'),
        ),
    ]
