# Generated by Django 5.2.8 on 2025-11-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_certificate_options_and_more'),
    ]

    operations = [
        # Remove all foreign key fields first
        migrations.RemoveField(
            model_name='markedquestion',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='markedquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='student',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='test',
        ),
        # Now delete the models
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='MarkedQuestion',
        ),
        migrations.DeleteModel(
            name='TestAnswer',
        ),
        migrations.DeleteModel(
            name='TestAttempt',
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
