# Generated by Django 5.2.8 on 2025-11-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportTicket',
        ),
    ]
