# Generated by Django 5.2.8 on 2025-11-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_remove_support_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1, help_text='Points/marks for this question'),
        ),
    ]
