# Generated by Django 5.2.8 on 2025-11-25 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_question_marks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, default='#667eea', help_text='Hex color code (e.g., #667eea)', max_length=7)),
                ('icon', models.CharField(blank=True, default='fas fa-folder', help_text='FontAwesome icon class', max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='questions.questionfolder')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='folders',
            field=models.ManyToManyField(blank=True, help_text='Folders this question belongs to', related_name='questions', to='questions.questionfolder'),
        ),
        migrations.AddIndex(
            model_name='questionfolder',
            index=models.Index(fields=['created_by', 'parent'], name='questions_q_created_3a8b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='questionfolder',
            index=models.Index(fields=['is_archived'], name='questions_q_is_arch_94bf90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionfolder',
            unique_together={('created_by', 'parent', 'name')},
        ),
    ]
