# Generated by Django 5.2.8 on 2025-11-25 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_questionfolder_question_folders_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(default='#667eea', max_length=7)),
                ('icon', models.CharField(default='fas fa-folder', max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='questions.materialfolder')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='materials', to='questions.materialfolder'),
        ),
        migrations.AddIndex(
            model_name='materialfolder',
            index=models.Index(fields=['created_by', 'parent'], name='questions_m_created_e4abe7_idx'),
        ),
        migrations.AddIndex(
            model_name='materialfolder',
            index=models.Index(fields=['is_archived'], name='questions_m_is_arch_8866d3_idx'),
        ),
    ]
