# Generated by Django 5.2.8 on 2025-11-25 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_materialfolder_resource_folders_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color code for tag badge (e.g., #3b82f6)', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False, help_text='Global tags are available to all teachers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing this question', related_name='questions', to='questions.tag'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['created_by', 'name'], name='questions_t_created_da6ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_global'], name='questions_t_is_glob_55838a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('created_by', 'name')},
        ),
    ]
