from django.urls import path
from .views import (
    questions_list,
    add_question,
    edit_question,
    delete_question,
    take_question,
    submissions_list,
    grade_submission,
    grade_test_attempt,
    leaderboard,
    export_performance_csv,
    student_submissions,
    tests_list,
    add_test,
    available_tests,
    start_test,
    submit_test,
    review_test,
    attempts_list,
    grade_attempt,
    paper_builder,
    edit_paper,
    send_test_reminder,
    # Folder management
    folder_list,
    create_folder,
    edit_folder,
    delete_folder,
    move_questions_to_folder,
    get_folders_json,
    # Materials
    student_materials,
    teacher_materials,
    upload_material,
    delete_material,
    # Material Folders
    create_material_folder,
    edit_material_folder,
    delete_material_folder,
    move_materials_to_folder,
    get_material_folders_json,
    # Student Dashboard
    student_dashboard,
    student_all_exams,
    student_upcoming_exams,
    student_attempted_exams,
    student_pyqs,
    student_results,
    download_result_report,
    download_cumulative_report,
    student_notifications,
    mark_notification_read,
    view_leaderboard,
    view_certificates,
    auto_save_answer,
    mark_question_for_review,
)
from .subject_api import get_subjects, add_subject
from .tag_views import (
    tag_list,
    create_tag,
    edit_tag,
    delete_tag,
    assign_tags,
    get_tags_json,
)

urlpatterns = [
    path('', questions_list, name='questions_list'),
    path('add/', add_question, name='add_question'),
    path('edit/<int:id>/', edit_question, name='edit_question'),
    path('delete/<int:id>/', delete_question, name='delete_question'),
    path('take/<int:id>/', take_question, name='take_question'),
    path('submissions/', submissions_list, name='submissions_list'),
    path('grade/<int:id>/', grade_submission, name='grade_submission'),
    path('grade-test/<int:attempt_id>/', grade_test_attempt, name='grade_test_attempt'),
    path('leaderboard/', leaderboard, name='leaderboard'),
    path('export/performance.csv', export_performance_csv, name='export_performance_csv'),
    path('me/submissions/', student_submissions, name='student_submissions'),
    # Folders
    path('folders/', folder_list, name='folder_list'),
    path('folders/create/', create_folder, name='create_folder'),
    path('folders/<int:folder_id>/edit/', edit_folder, name='edit_folder'),
    path('folders/<int:folder_id>/delete/', delete_folder, name='delete_folder'),
    path('folders/move-questions/', move_questions_to_folder, name='move_questions_to_folder'),
    path('api/folders/', get_folders_json, name='get_folders_json'),
    # Tests
    path('tests/', tests_list, name='tests_list'),
    path('tests/add/', add_test, name='add_test'),
    path('tests/paper-builder/', paper_builder, name='paper_builder'),
    path('tests/<int:test_id>/edit/', edit_paper, name='edit_paper'),
    path('tests/<int:test_id>/send-reminder/', send_test_reminder, name='send_test_reminder'),
    # Student test taking
    path('tests/available/', available_tests, name='available_tests'),
    path('tests/start/<int:test_id>/', start_test, name='start_test'),
    path('tests/submit/<int:attempt_id>/', submit_test, name='submit_test'),
    path('tests/review/<int:attempt_id>/', review_test, name='review_test'),
    # Teacher attempts and grading
    path('tests/<int:test_id>/attempts/', attempts_list, name='attempts_list'),
    path('tests/attempts/<int:attempt_id>/grade/', grade_attempt, name='grade_attempt'),
    # Materials & resources
    path('materials/', student_materials, name='student_materials'),
    path('materials/teacher/', teacher_materials, name='teacher_materials'),
    path('materials/upload/', upload_material, name='upload_material'),
    path('materials/delete/<int:resource_id>/', delete_material, name='delete_material'),
    # Material Folders
    path('materials/folders/create/', create_material_folder, name='create_material_folder'),
    path('materials/folders/<int:folder_id>/edit/', edit_material_folder, name='edit_material_folder'),
    path('materials/folders/<int:folder_id>/delete/', delete_material_folder, name='delete_material_folder'),
    path('materials/folders/move/', move_materials_to_folder, name='move_materials_to_folder'),
    path('materials/api/folders/', get_material_folders_json, name='get_material_folders_json'),
    # Student Dashboard
    path('dashboard/', student_dashboard, name='student_dashboard'),
    path('exams/all/', student_all_exams, name='student_all_exams'),
    path('exams/upcoming/', student_upcoming_exams, name='student_upcoming_exams'),
    path('exams/attempted/', student_attempted_exams, name='student_attempted_exams'),
    path('exams/pyqs/', student_pyqs, name='student_pyqs'),
    path('results/', student_results, name='student_results'),
    path('results/download/<int:attempt_id>/', download_result_report, name='download_result_report'),
    path('results/cumulative/', download_cumulative_report, name='download_cumulative_report'),
    path('notifications/', student_notifications, name='student_notifications'),
    path('notifications/read/<int:notification_id>/', mark_notification_read, name='mark_notification_read'),
    path('leaderboard/view/', view_leaderboard, name='view_leaderboard'),
    path('certificates/', view_certificates, name='view_certificates'),
    # AJAX endpoints
    path('api/auto-save/', auto_save_answer, name='auto_save_answer'),
    path('api/mark-review/', mark_question_for_review, name='mark_question_for_review'),
    # Subject API endpoints
    path('api/subjects/', get_subjects, name='get_subjects'),
    path('api/subjects/add/', add_subject, name='add_subject'),
    # Tag management
    path('tags/', tag_list, name='tag_list'),
    path('tags/create/', create_tag, name='create_tag'),
    path('tags/<int:tag_id>/edit/', edit_tag, name='edit_tag'),
    path('tags/<int:tag_id>/delete/', delete_tag, name='delete_tag'),
    path('tags/assign/', assign_tags, name='assign_tags'),
    path('api/tags/', get_tags_json, name='get_tags_json'),
]
