# Generated by Django 5.2.8 on 2025-11-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_user_ty_8de000_idx',
            old_name='authenticat_user_ty_3b2fff_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_email_5ce40b_idx',
            old_name='authenticat_email_486e08_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'teacher'), (3, 'student')], default=3),
        ),
    ]
