# Generated by Django 5.2.7 on 2025-11-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_authenticat_user_ty_3b2fff_idx_accounts_cu_user_ty_8de000_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
