# Generated by Django 5.2.7 on 2025-11-19 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ScheduledTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tests', to=settings.AUTH_USER_MODEL)),
                ('test_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_instances', to='exams.test')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['status', '-start_time'], name='exams_sched_status_8b2328_idx'), models.Index(fields=['is_published', 'start_time'], name='exams_sched_is_publ_851de9_idx')],
            },
        ),
    ]
