# Generated by Django 5.2.8 on 2025-11-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_test_total_marks_scheduledtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Section name like "Section A", "Part I", etc.', max_length=100),
        ),
    ]
