# Generated by Django 5.2.8 on 2025-11-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_testquestion_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['section', 'order', 'id']},
        ),
    ]
